name: Deploy Thryve

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: 'Thryve/thryve-strapi-backend/.nvmrc'

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/projects/Thryve
            git pull origin main
            cd thryve-frontend && npm install && npm run build
            cd ../thryve-strapi-backend && npm install --force
            sudo systemctl restart thryve-frontend thryve-strapi-backend
