name: Deploy Thryve

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Node version from .nvmrc
        id: node_version
        # Note: This step is actually only useful for the runner, but kept for clarity 
        # that the version is being identified. The version on the server will be 
        # handled by 'nvm use'.
        run: echo "NODE_VERSION=$(cat thryve-strapi-backend/.nvmrc)" >> $GITHUB_ENV

      - name: Setup Node.js on Runner (Not Server)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Deploy and Build on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Exit immediately if any command fails
            set -e

            # Navigate to the repository root
            cd /var/www/projects/Thryve
            git pull origin main

            # --- Frontend Build ---
            cd thryve-frontend
            npm install
            npm run build

            # --- Backend Install ---
            cd ../thryve-strapi-backend
            rm -rf node_modules

            # Source NVM manually for non-login shell access
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Use the version specified in the .nvmrc file
            nvm use
            
            # Install dependencies
            npm install
            
            # Note: Do NOT run 'npm run dev' or 'npm run start' here. 
            # Your systemd service must handle starting the application.

            # --- Restart Services ---
            sudo systemctl restart thryve-frontend thryve-strapi-backend